"""
LLM Classifier: wraps RAGEngine to produce ClassifiedTransaction objects
for fitness-related transactions.

Only transactions flagged as fitness-related by ATOKnowledgeBase.is_fitness_related()
are sent through the RAG pipeline. All others are returned untouched.
"""

from typing import List, Optional

from backend.models.schemas import (
    ClassifiedTransaction,
    NormalisedTransaction,
    DeductionCategory,
    EvidenceType,
)
from backend.rag.rag_engine import RAGEngine, RAGResult


# Map RAG category strings to DeductionCategory enum values
_CATEGORY_ENUM_MAP = {
    "fitness_related": DeductionCategory.FITNESS_RELATED,
    "training_education": DeductionCategory.TRAINING_EDUCATION,
}

# Map evidence string labels to EvidenceType enum values
_EVIDENCE_MAP = {
    "receipt": EvidenceType.RECEIPT,
    "invoice": EvidenceType.INVOICE,
    "diary": EvidenceType.DIARY,
    "percentage_record": EvidenceType.PERCENTAGE_RECORD,
    "logbook": EvidenceType.LOGBOOK,
    "eligibility_check": EvidenceType.ELIGIBILITY_CHECK,
    # Catch-all aliases
    "work diary": EvidenceType.DIARY,
    "work_diary": EvidenceType.DIARY,
    "tax invoice": EvidenceType.INVOICE,
    "tax_invoice": EvidenceType.INVOICE,
    "employment contract": EvidenceType.DIARY,  # closest available type
}

RAG_RULE_ID_PREFIX = "RAG-FITNESS"
RAG_RULE_VERSION = "rag-2025"

DISCLAIMER = (
    "NOT TAX ADVICE — This analysis is generated by AI and is for informational "
    "purposes only. Always consult a registered tax agent (BAS agent) or contact "
    "the ATO directly before claiming any deduction."
)


class LLMClassifier:
    """
    Classifies fitness-related transactions using RAG + Claude.

    For every transaction in a batch:
    - If fitness-related: run RAG, produce a ClassifiedTransaction with RAG metadata.
    - Otherwise: return the transaction unchanged (pass-through).

    The classifier never overwrites a high-confidence rule-based classification;
    it only replaces unclassified (confidence == 0) or low-confidence results
    where the RAG score is higher.
    """

    def __init__(
        self,
        rag_engine: RAGEngine,
        confidence_threshold: float = 0.40,
        override_threshold: float = 0.60,
    ):
        """
        Args:
            rag_engine: Initialised RAGEngine instance.
            confidence_threshold: Minimum RAG confidence to assign a category.
            override_threshold: Only replace existing classification if RAG confidence
                                 exceeds this threshold (avoids downgrading good rule matches).
        """
        self.rag = rag_engine
        self.confidence_threshold = confidence_threshold
        self.override_threshold = override_threshold

    def enhance(
        self,
        classified: List[ClassifiedTransaction],
    ) -> List[ClassifiedTransaction]:
        """
        Enhance classified transactions with RAG analysis where applicable.

        For each classified transaction:
        - Skip if existing confidence >= override_threshold (rule already did well).
        - If fitness-related and RAG available: run RAG and merge result.

        Args:
            classified: Output from the rule-based ClassificationEngine.

        Returns:
            Same list with fitness transactions enriched by RAG analysis.
        """
        if not self.rag.available and not self.rag.kb.is_fitness_related("", ""):
            return classified

        enhanced = []
        for ct in classified:
            txn = ct.transaction
            is_fitness = self.rag.kb.is_fitness_related(txn.description, txn.merchant)

            # Skip: rule-based engine already classified it with high confidence
            if ct.confidence >= self.override_threshold and not is_fitness:
                enhanced.append(ct)
                continue

            if not is_fitness:
                enhanced.append(ct)
                continue

            # Run RAG
            rag_result = self.rag.classify_transaction(
                description=txn.description,
                merchant=txn.merchant,
                amount=float(txn.absolute_amount),
            )

            merged = self._merge(ct, rag_result)
            enhanced.append(merged)

        return enhanced

    # ------------------------------------------------------------------ #
    # Private helpers
    # ------------------------------------------------------------------ #

    def _merge(
        self,
        original: ClassifiedTransaction,
        rag: RAGResult,
    ) -> ClassifiedTransaction:
        """
        Merge RAG result into the original ClassifiedTransaction.

        Strategy:
        - If RAG confidence > original confidence: use RAG category + confidence.
        - Always append RAG reason, ATO citation, and disclaimer to reason field.
        - Always append RAG evidence requirements not already in checklist.
        - Always add "rag_analysed" flag and occupation_dependent flag if applicable.
        """
        rag_confidence = rag.confidence_float

        # Decide category and confidence
        if rag_confidence > original.confidence:
            new_category = self._map_category(rag)
            new_confidence = rag_confidence
            new_rule_id = f"{RAG_RULE_ID_PREFIX}-{rag.category.upper()}"
            new_rule_version = RAG_RULE_VERSION
        else:
            new_category = original.category
            new_confidence = original.confidence
            new_rule_id = original.matched_rule_id
            new_rule_version = original.matched_rule_version

        # Build enriched reason string
        rag_reason = (
            f"[RAG] {rag.reason} "
            f"| ATO: {rag.ato_citation} "
            f"| Score: keyword={rag.keyword_score}/30 "
            f"grounding={rag.rag_grounding_score}/40 "
            f"claude={rag.claude_score}/30"
        )
        if rag.conditions:
            rag_reason += f" | Conditions: {'; '.join(rag.conditions)}"
        rag_reason += f" | {DISCLAIMER}"

        combined_reason = (
            f"{original.reason} {rag_reason}".strip()
            if original.reason and original.reason != "no_rule_matched"
            else rag_reason
        )

        # Merge evidence checklists
        existing_evidence = set(original.evidence_checklist)
        for ev_str in rag.evidence_required:
            ev_type = _EVIDENCE_MAP.get(ev_str.lower().strip())
            if ev_type and ev_type not in existing_evidence:
                existing_evidence.add(ev_type)

        # Merge flags
        flags = list(original.flags)
        flags.append("rag_analysed")
        if rag.occupation_dependent and "occupation_dependent" not in flags:
            flags.append("occupation_dependent")
        if not rag.is_potentially_deductible and "needs_review" not in flags:
            flags.append("needs_review")

        return ClassifiedTransaction.model_construct(
            transaction=original.transaction,
            category=new_category,
            confidence=new_confidence,
            matched_rule_id=new_rule_id,
            matched_rule_version=new_rule_version,
            reason=combined_reason,
            evidence_checklist=list(existing_evidence),
            flags=flags,
        )

    def _map_category(self, rag: RAGResult) -> Optional[DeductionCategory]:
        """Map RAG category string to DeductionCategory enum, or None."""
        if not rag.is_potentially_deductible:
            return None
        mapped = _CATEGORY_ENUM_MAP.get(rag.mapped_category or "")
        if mapped:
            return mapped
        if rag.category == "training_education":
            return DeductionCategory.TRAINING_EDUCATION
        return DeductionCategory.FITNESS_RELATED
